spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_rafy4j?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    com.github.zgynhqf.rafy4j.data.SimpleDbAccessor: debug

mybatis-plus:
  mapper-locations: [classpath:mapper/*Mapper.xml]
  #实体扫描，多个package用逗号或者分号分隔
  # typeEnumsPackage: com.baomidou.springboot.entity.enums
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      #      field-strategy: not_empty
      #数据库大写下划线转换
      #      capital-mode: true
      #逻辑删除配置
      #      logic-delete-value: 0
      #      logic-not-delete-value: 1
      db-type: mysql